package handler

import (
	"bytes"
	"context"
	"errors"
	"io"
	"net/http"
	"path/filepath"
	"strings"

	"hill-images/internal/models"
	"hill-images/internal/storage"

	"github.com/gin-gonic/gin"
)

func (h *FileHandler) ServeLocalPretty(c *gin.Context) {
	if h.storage.Driver() != storage.DriverLocal {
		fileError(c, http.StatusNotFound, "image not found", "NOT_FOUND")
		return
	}

	fullPath := c.Request.URL.Path
	fullPath = strings.TrimPrefix(fullPath, "/")
	if fullPath == "" {
		fileError(c, http.StatusBadRequest, "invalid local image path", "VALIDATION_ERROR")
		return
	}

	parts := strings.SplitN(fullPath, "/", 2)
	if isYearSegment(parts[0]) && len(parts) == 2 {
		year := parts[0]
		name := filepath.Base(parts[1])
		if name == "" || name == "." {
			fileError(c, http.StatusBadRequest, "invalid local image path", "VALIDATION_ERROR")
			return
		}
		img, err := h.imageService.FindLocalByPublicPath(year, name)
		if err != nil {
			fileError(c, http.StatusNotFound, "image not found", "NOT_FOUND")
			return
		}
		h.serveImage(c, img)
		return
	}

	prettyName := filepath.Base(fullPath)
	img, err := h.imageService.FindLocalByPrettyName(prettyName)
	if err != nil {
		fileError(c, http.StatusNotFound, "image not found", "NOT_FOUND")
		return
	}
	h.serveImage(c, img)
}

func isYearSegment(s string) bool {
	if len(s) != 4 {
		return false
	}
	for _, ch := range s {
		if ch < '0' || ch > '9' {
			return false
		}
	}
	return true
}

func (h *FileHandler) serveImage(c *gin.Context, img *models.Image) {
	stream, err := h.storage.Open(c.Request.Context(), img.Path)
	if err != nil {
		if errors.Is(err, storage.ErrNotFound) {
			fileError(c, http.StatusNotFound, "file not found", "NOT_FOUND")
			return
		}
		fileError(c, http.StatusInternalServerError, "failed to open file", "OPEN_FAILED")
		return
	}
	defer stream.Close()
	c.Header("Content-Type", img.MimeType)
	c.Header("Cache-Control", "public, max-age=31536000")
	c.Status(http.StatusOK)
	_, _ = io.Copy(c.Writer, stream)
}

// ServeThumb handles GET /api/files/:hash/thumb — serve or generate thumbnail.
//
// Thumbnails are always stored in the same storage backend as the original.
// For the local driver the thumb is read back from disk with os.Stat-style
// checks; for R2 the existence check uses a HEAD on the thumb key.
//
// Under R2 the source image must be fetched from the bucket before the
// thumbnail generator can decode it, so the first request for a given
// hash performs an R2 GET. The generated bytes are then written back as
// a separate "thumbs/<hash>.webp" object.
func (h *FileHandler) ServeThumb(c *gin.Context) {
	hash := c.Param("hash")
	if hash == "" {
		fileError(c, http.StatusBadRequest, "missing hash", "VALIDATION_ERROR")
		return
	}

	img, err := h.imageService.GetByHash(hash)
	if err != nil {
		fileError(c, http.StatusNotFound, "image not found", "NOT_FOUND")
		return
	}

	if img.MimeType == "image/svg+xml" {
		if h.serveOriginalThumb(c, img) {
			return
		}
		fileError(c, http.StatusInternalServerError, "failed to serve source image", "SOURCE_FAILED")
		return
	}

	thumbKey := hash + ".webp"

	// Try the existing thumbnail first.
	if r2, ok := h.storage.(*storage.R2Storage); ok {
		stream, err := r2.OpenThumb(c.Request.Context(), thumbKey)
		if err == nil {
			defer stream.Close()
			c.Header("Content-Type", "image/webp")
			c.Header("Cache-Control", "public, max-age=31536000")
			c.Status(http.StatusOK)
			_, _ = io.Copy(c.Writer, stream)
			return
		}
		if !errors.Is(err, storage.ErrNotFound) {
			fileError(c, http.StatusInternalServerError, "failed to read thumb", "THUMB_READ_FAILED")
			return
		}
	} else if local, ok := h.storage.(*storage.LocalStorage); ok {
		// Local: the on-disk check is cheap.
		thumbPath, safeErr := local.ThumbPath(thumbKey)
		if safeErr == nil {
			if _, statErr := osStat(thumbPath); statErr == nil {
				c.Header("Content-Type", "image/webp")
				c.Header("Cache-Control", "public, max-age=31536000")
				c.File(thumbPath)
				return
			}
		}
	}

	// Generate a new thumbnail from the source image.
	src, err := openSourceForThumb(c.Request.Context(), h.storage, img)
	if err != nil {
		if h.serveOriginalThumb(c, img) {
			return
		}
		fileError(c, http.StatusInternalServerError, "failed to open source image", "OPEN_FAILED")
		return
	}
	defer src.Close()

	thumbData, err := generateThumbnail(src, img.MimeType)
	if err != nil {
		if h.serveOriginalThumb(c, img) {
			return
		}
		fileError(c, http.StatusInternalServerError, "failed to generate thumbnail", "THUMB_FAILED")
		return
	}

	if err := h.storage.SaveThumb(c.Request.Context(), thumbKey, bytes.NewReader(thumbData)); err != nil {
		if h.serveOriginalThumb(c, img) {
			return
		}
		fileError(c, http.StatusInternalServerError, "failed to save thumbnail", "THUMB_SAVE_FAILED")
		return
	}

	img.ThumbPath = thumbKey
	_ = h.imageService.UpdateThumbPath(img)

	c.Data(http.StatusOK, "image/webp", thumbData)
}

func (h *FileHandler) serveOriginalThumb(c *gin.Context, img *models.Image) bool {
	src, err := openSourceForThumb(c.Request.Context(), h.storage, img)
	if err != nil {
		if errors.Is(err, storage.ErrNotFound) {
			fileError(c, http.StatusNotFound, "file not found", "NOT_FOUND")
			return true
		}
		return false
	}
	defer src.Close()

	c.Header("Content-Type", img.MimeType)
	c.Header("Cache-Control", "public, max-age=31536000")
	c.Status(http.StatusOK)
	_, _ = io.Copy(c.Writer, src)
	return true
}

// openSourceForThumb returns a reader positioned at the start of the original
// image bytes, regardless of the underlying storage driver. The local driver
// keeps the existing fast-path that opens the file on disk directly so the
// thumbnail generator can use the OS page cache.
func openSourceForThumb(ctx context.Context, s storage.Storage, img *models.Image) (io.ReadCloser, error) {
	if local, ok := s.(*storage.LocalStorage); ok {
		// The Image row may store either an absolute path (legacy rows
		// written before the storage refactor) or a relative key
		// ("2026/06/..._..._<hash>.jpg"). LocalStorage.Path returns the
		// correct on-disk path in both cases.
		p, pathErr := local.Path(img.Path)
		if pathErr != nil {
			return nil, pathErr
		}
		return openFile(p)
	}
	return s.Open(ctx, img.Path)
}

// generateThumbnail is the bytes-based entry point for thumbnail generation;
// the underlying logic lives in thumbnail.go alongside the resize helpers.
func generateThumbnail(r io.Reader, mimeType string) ([]byte, error) {
	return generateThumbnailFromReader(r, mimeType)
}
